# Generated by Django 2.0.3 on 2018-04-05 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comingNext',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pub_date',
        ),
    ]
