# Generated by Django 2.0.3 on 2018-04-05 04:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180405_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 5, 4, 10, 38, 303550, tzinfo=utc), verbose_name='Publish Date'),
            preserve_default=False,
        ),
    ]
