# Generated by Django 2.0.3 on 2018-03-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=200)),
                ('Category', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=200)),
                ('Content', models.CharField(max_length=200)),
                ('Private', models.CharField(max_length=20)),
                ('comingNext', models.CharField(blank=True, max_length=100, null=True)),
                ('pub_date', models.DateTimeField(verbose_name='Publish Date')),
            ],
        ),
    ]
